fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    apt: "https://github.com/puppetlabs/puppetlabs-apt.git"
    zypprepo: "https://github.com/deadpoint/puppet-zypprepo.git"
    inifile: "https://github.com/puppetlabs/puppetlabs-inifile.git"
    archive: "https://github.com/voxpupuli/puppet-archive.git"
  symlinks:
    php: "#{source_dir}"
